"""Project and CSV file IO helpers."""

from __future__ import annotations

import csv
import json
from pathlib import Path

from core.models import CHANNELS, MeasurementEvent, Project, WaveformPoint


WAVEFORM_COLUMNS = ["Channel", "Time [s]", "Voltage [V]"]
MEASUREMENT_COLUMNS = ["tm [s]", "Points", "Interval [s]", "Averaging [s]", "Ch1 Range", "Ch2 Range"]
CONFIG_COLUMNS = ["Kind", *WAVEFORM_COLUMNS, *MEASUREMENT_COLUMNS]


def save_project(path: str | Path, project: Project) -> None:
    """Save a project JSON file."""

    Path(path).write_text(json.dumps(project.to_dict(), indent=2), encoding="utf-8")


def load_project(path: str | Path) -> Project:
    """Load a project JSON file."""

    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    return Project.from_dict(payload)


def export_waveforms_csv(path: str | Path, project: Project) -> None:
    """Export both waveform channels to a single CSV."""

    with Path(path).open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=WAVEFORM_COLUMNS)
        writer.writeheader()
        for channel in CHANNELS:
            for point in project.waveforms[channel]:
                writer.writerow({"Channel": channel.upper(), "Time [s]": point.time, "Voltage [V]": point.voltage})


def import_waveforms_csv(path: str | Path, project: Project) -> Project:
    """Import a waveform CSV generated by this application."""

    rows = _read_csv_rows(path)
    next_project = project.clone()
    for channel in CHANNELS:
        label = channel.upper()
        next_project.waveforms[channel] = [
            WaveformPoint(_float(row["Time [s]"]), _float(row["Voltage [V]"]))
            for row in rows
            if row.get("Channel", "").upper() == label
        ]
    next_project.enforce_monotonic_waveforms(next_project.settings.minimum_point_spacing)
    return next_project


def export_measurements_csv(path: str | Path, project: Project) -> None:
    """Export measurement events to CSV."""

    with Path(path).open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=MEASUREMENT_COLUMNS)
        writer.writeheader()
        for event in project.measurements:
            writer.writerow(_measurement_row(event))


def import_measurements_csv(path: str | Path, project: Project) -> Project:
    """Import measurement events from CSV."""

    rows = _read_csv_rows(path)
    next_project = project.clone()
    next_project.measurements = [
        _measurement_from_row(row)
        for row in rows
    ]
    return next_project


def export_config_csv(path: str | Path, project: Project) -> None:
    """Export CH1/CH2 waveforms and measurements to one CSV config file."""

    with Path(path).open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=CONFIG_COLUMNS)
        writer.writeheader()
        for channel in CHANNELS:
            for point in project.waveforms[channel]:
                writer.writerow(
                    {
                        "Kind": "Waveform",
                        "Channel": channel.upper(),
                        "Time [s]": point.time,
                        "Voltage [V]": point.voltage,
                    }
                )
        for event in project.measurements:
            row = {"Kind": "Measurement"}
            row.update(_measurement_row(event))
            writer.writerow(row)


def import_config_csv(path: str | Path, project: Project | None = None) -> Project:
    """Import one CSV config file containing waveforms and measurements."""

    rows = _read_csv_rows(path)
    next_project = project.clone() if project is not None else Project()

    for channel in CHANNELS:
        label = channel.upper()
        next_project.waveforms[channel] = [
            WaveformPoint(_float(row["Time [s]"]), _float(row["Voltage [V]"]))
            for row in rows
            if row.get("Kind", "").strip().lower() == "waveform"
            and row.get("Channel", "").upper() == label
            and _has_value(row.get("Time [s]"))
            and _has_value(row.get("Voltage [V]"))
        ]

    next_project.measurements = [
        _measurement_from_row(row)
        for row in rows
        if row.get("Kind", "").strip().lower() == "measurement"
        and _has_value(row.get("tm [s]"))
    ]
    next_project.enforce_monotonic_waveforms(next_project.settings.minimum_point_spacing)
    return next_project


def _read_csv_rows(path: str | Path) -> list[dict[str, str]]:
    with Path(path).open(newline="", encoding="utf-8-sig") as file:
        return list(csv.DictReader(file))


def _has_value(value: str | None) -> bool:
    return value is not None and str(value).strip() != ""


def _float(value: str | None, default: float = 0.0) -> float:
    return float(value) if _has_value(value) else default


def _int(value: str | None, default: int = 0) -> int:
    return int(float(value)) if _has_value(value) else default


def _measurement_row(event: MeasurementEvent) -> dict[str, float | int]:
    return {
        "tm [s]": event.tm,
        "Points": event.points,
        "Interval [s]": event.interval,
        "Averaging [s]": event.averaging,
        "Ch1 Range": event.ch1_range,
        "Ch2 Range": event.ch2_range,
    }


def _measurement_from_row(row: dict[str, str]) -> MeasurementEvent:
    return MeasurementEvent(
        tm=_float(row.get("tm [s]")),
        points=_int(row.get("Points"), 1),
        interval=_float(row.get("Interval [s]"), 1e-6),
        averaging=_float(row.get("Averaging [s]"), 1e-6),
        ch1_range=_float(row.get("Ch1 Range")),
        ch2_range=_float(row.get("Ch2 Range")),
    )
