"""Project and CSV file IO helpers."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from core.models import CHANNELS, MeasurementEvent, Project, WaveformPoint


def save_project(path: str | Path, project: Project) -> None:
    """Save a project JSON file."""

    Path(path).write_text(json.dumps(project.to_dict(), indent=2), encoding="utf-8")


def load_project(path: str | Path) -> Project:
    """Load a project JSON file."""

    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    return Project.from_dict(payload)


def export_waveforms_csv(path: str | Path, project: Project) -> None:
    """Export both waveform channels to a single CSV."""

    rows = []
    for channel in CHANNELS:
        for point in project.waveforms[channel]:
            rows.append({"Channel": channel.upper(), "Time [s]": point.time, "Voltage [V]": point.voltage})
    pd.DataFrame(rows, columns=["Channel", "Time [s]", "Voltage [V]"]).to_csv(path, index=False)


def import_waveforms_csv(path: str | Path, project: Project) -> Project:
    """Import a waveform CSV generated by this application."""

    df = pd.read_csv(path)
    next_project = project.clone()
    for channel in CHANNELS:
        label = channel.upper()
        sub = df[df["Channel"].astype(str).str.upper() == label]
        next_project.waveforms[channel] = [
            WaveformPoint(float(row["Time [s]"]), float(row["Voltage [V]"]))
            for _, row in sub.iterrows()
        ]
    next_project.sort_waveforms()
    return next_project


def export_measurements_csv(path: str | Path, project: Project) -> None:
    """Export measurement events to CSV."""

    project.measurement_df().to_csv(path, index=False)


def import_measurements_csv(path: str | Path, project: Project) -> Project:
    """Import measurement events from CSV."""

    df = pd.read_csv(path)
    next_project = project.clone()
    next_project.measurements = [
        MeasurementEvent(
            tm=float(row["tm [s]"]),
            points=int(row["Points"]),
            interval=float(row["Interval [s]"]),
            averaging=float(row["Averaging [s]"]),
            ch1_range=float(row["Ch1 Range"]),
            ch2_range=float(row["Ch2 Range"]),
        )
        for _, row in df.iterrows()
    ]
    return next_project
